services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.3.2
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      args:
        RUBY_VERSION: 3.3.2
    command: ["bundle", "exec", "sidekiq", "-e", "development"]
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  db_data:
